version: '3.8'
services:
  # Postgres Database
  postgres:
    image: postgres:15-alpine
    container_name: dev_postgres
    environment:
      POSTGRES_DB: fypbackend
      POSTGRES_USER: joshua
      POSTGRES_PASSWORD: joshua
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U joshua -d fypbackend"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: dev_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Gorse Recommendation Engine
  gorse:
    image: zhenghaoz/gorse-in-one
    container_name: dev_gorse
    restart: unless-stopped
    ports:
      - "8088:8088"
      - "8086:8086"  
    environment:
      # Using PostgreSQL as data store
      GORSE_DATA_STORE: postgres://joshua:joshua@postgres:5432/fypbackend?sslmode=disable
      # Using Redis as cache store
      GORSE_CACHE_STORE: redis://redis:6379/0
      # Optional: Configure other Gorse settings
      GORSE_MASTER_HOST: 0.0.0.0
      GORSE_MASTER_PORT: 8086
      GORSE_HTTP_HOST: 0.0.0.0
      GORSE_HTTP_PORT: 8088
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - gorse_data:/var/lib/gorse

  # Go App (for production-like testing)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev_app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=joshua
      - DB_PASSWORD=joshua
      - DB_NAME=fypbackend
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ENV=development
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    # Remove this section if you want to run Go locally
    profiles:
      - production-test

volumes:
  postgres_data:
  redis_data:
  gorse_data:
